### ISSUE TITLE
目前api已经是可用状态了吗

### ISSUE THREAD

**Issue by amokiel** [Dituon/pixiv-api-http#1]
开发者辛苦了，感觉这个项目很有用。问下目前api是已经可以配置到第三方应用里面了吗，多谢！

**Comment by Dituon** [comment]
不胜荣幸，目前已实现的功能详见文档，是可用状态。

欢迎加入交流群: `828350277`

**Comment by amokiel** [comment]
> 不胜荣幸，目前已实现的功能详见文档，是可用状态。
> 
> 欢迎加入交流群: `828350277`

感谢回复。请教一下，这个api理论上直连速度，要比shaft，pixez这些pixiv第三方应用实现的效果要快吗，还是说各方面实现的效果要更优异一些。不太懂api方面的知识，如有冒昧，还请见谅。另外这个api是否可以提供给那些pixiv第三方项目的开发者，以实现更优异的浏览体验呢。多谢开发者的付出！

**Comment by Dituon** [comment]
### 速度 / 性能

「直连速度」为字面意思, 本地直接访问Pixiv, 不通过第三方服务器。

直接连接: `本地 => Pixiv`
第三方API: `本地 => 第三方代理 => Pixiv` 

访问速度取决于网络环境, 欢迎进行基准测试

### 稳定性

第三方API可能因为各种原因停止服务(如受到攻击等), 本地搭建稳定性更胜一筹

### 局限

进行高级搜索 需提供Pixiv高级账户, 第三方API可直接调用, 相当于大家共用一个高级账户

**Comment by amokiel** [comment]
> ### 速度 / 性能
> 「直连速度」为字面意思, 本地直接访问Pixiv, 不通过第三方服务器。
> 
> 直接连接: `本地 => Pixiv` 第三方API: `本地 => 第三方代理 => Pixiv`
> 
> 访问速度取决于网络环境, 欢迎进行基准测试
> 
> ### 稳定性
> 第三方API可能因为各种原因停止服务(如受到攻击等), 本地搭建稳定性更胜一筹
> 
> ### 局限
> 进行高级搜索 需提供Pixiv高级账户, 第三方API可直接调用, 相当于大家共用一个高级账户

也就是说，这个api提供给pixiv第三方客户端开发者，能够使应用体验更好吧。那样的话，可以提供给shaft和pixez项目，他们合并一下实现方式，应该会更好用。

**Comment by amokiel** [comment]
> ### 速度 / 性能
> 「直连速度」为字面意思, 本地直接访问Pixiv, 不通过第三方服务器。
> 
> 直接连接: `本地 => Pixiv` 第三方API: `本地 => 第三方代理 => Pixiv`
> 
> 访问速度取决于网络环境, 欢迎进行基准测试
> 
> ### 稳定性
> 第三方API可能因为各种原因停止服务(如受到攻击等), 本地搭建稳定性更胜一筹
> 
> ### 局限
> 进行高级搜索 需提供Pixiv高级账户, 第三方API可直接调用, 相当于大家共用一个高级账户

如果可以的话，我可以去shaft和pixez那边提个Issues，尝试一下新的实现方式也挺好的。

**Comment by Dituon** [comment]
1. 此API的开发初衷运行环境更接近于服务端, 而非客户端
2. 不建议移动端开发直接使用NodeJS实现
3. 可参考此API实现方式进行重写, 以适配移动端环境

**Comment by amokiel** [comment]
> 1. 此API的开发初衷运行环境更接近于服务端, 而非客户端
> 2. 不建议移动端开发直接使用NodeJS实现
> 3. 可参考此API实现方式进行重写, 以适配移动端环境

也就是说，这个api还是能够实现在移动端第三方客户端的吗？刚才我已经去shaft那边提了个Issues，shaft是我常用的第三方客户端，因此希望shaft能够在移动端有更好的直连体验，所以特意询问了这么多相关情况。感谢开发者的耐心解答。

**Comment by Dituon** [comment]
1. 此API相较官方API风格有很大变动，更符合开发习惯，基于官方API实现的项目不建议直接使用
2. 此API基于NodeJS实现，移动端不建议直接使用
3. 此API直连方案可用移动端语言重写以实现此功能

**Comment by amokiel** [comment]
> 1. 此API相较官方API风格有很大变动，更符合开发习惯，基于官方API实现的项目不建议直接使用
> 2. 此API基于NodeJS实现，移动端不建议直接使用
> 3. 此API直连方案可用移动端语言重写以实现此功能

原来如此，有可能用得上就尽量试试，不过还是要看shaft开发者的想法了。还是多谢了！
