### ISSUE TITLE
错误：不正なリクエストです

### ISSUE THREAD

**Issue by KawakazeNotFound** [Dituon/pixiv-api-http#2]
配置好文件之后 程序抛出错误
>npm start
![image](https://github.com/user-attachments/assets/63c6b056-20d2-4a65-a29b-622fefa91946)
配置文件：
![image](https://github.com/user-attachments/assets/d1722aa0-1902-4822-994b-169d472d6dbc)
![image](https://github.com/user-attachments/assets/1e17c530-daf6-4ff6-bc3e-36a425a2ffb8)

**Comment by Dituon** [comment]
cookie 错误, 尝试重新获取。

0. 使用 `f12` 或 `ctrl` `shift` `i` 启用 **开发人员工具**。
1. 上方导航栏中选择 **网络**, 访问 [`www.pixiv.net`](https://www.pixiv.net)。
2. 在过滤器中选择 **文档**。
3. 选择 `www.pixiv.net` 请求。
4. 在 **请求标头** 中复制 **`Cookie`**字段。
5. 粘贴至配置文件 `config.js`。

![Steps to get cookies](https://github.com/user-attachments/assets/ce316e65-3905-4f56-89af-2f4cbedc19fb)
